### PR TITLE
Make the 'make install' works

### PR DESCRIPTION
**Pull request by jonadem**
For the make install to works, I replaces the spaces in the songs' filenames.
linthesia will now look for resources in the default directory or in the previous 'local' one.

A refactoring can be valuable but it should work as it is.

### CODE REVIEW

**Comment by allan-simon** [comment]
are you using it recently ? (I have to admit that now that I have an accoustic piano, I haven't touched to linthesia for quite some times now)

**Comment by jonadem** [comment]
A little bit. I gave it another try and I was able to use it this time. It is playable but still a little bit confusing (with #91 and #93). I have a [small midi keyboard](https://www.amazon.co.uk/ION-USB-Keyboard-Teaching-Software/dp/B003SOS5NY).

Although, for the moment, I have spent more time in the code than playing with it.

I hope that with this PR, it will be one step closer to be in distributions repositories. :-)

**Comment by allan-simon** [comment]
haha I hope too, 7 years I was sad that the original linthesia package was broken in ubuntu, and I hoped to fix it quickly, and here we are :P

**Comment by allan-simon** [comment]
I don't know if it's also possible to integrate in some way the patch that guy made here  #16  , because I remember that I found lacking the possibility to go backward/forward a bit by using arrow keys

**Pull request merged**
